/**
 * Static data loader for Phnom Penh buildings.
 *
 * Priority:
 *   1. /public/buildings_phnompenh.geojson  (generated by pipeline/fetch_buildings.py)
 *   2. OSMBuildings anonymous tile API       (live, viewport-based, zoom 15 only)
 *   3. Overpass API fallback                 (existing behaviour)
 *
 * The static file is the richest — it contains OSM + GBA + Overture merged data
 * with khan assignments and estimated heights.
 */

export const STATIC_GEOJSON_PATH = '/buildings_phnompenh.geojson'

/**
 * Try to load the pre-generated static GeoJSON.
 * Returns null if the file doesn't exist yet (pipeline not run).
 */
export async function loadStaticBuildings(signal) {
  try {
    const res = await fetch(STATIC_GEOJSON_PATH, { signal })
    if (!res.ok) return null
    const data = await res.json()
    if (!data?.features?.length) return null
    console.log(`[Static] Loaded ${data.features.length.toLocaleString()} buildings from static file`)
    return normalizeStaticFeatures(data.features)
  } catch (e) {
    if (e.name === 'AbortError') throw e
    return null
  }
}

/**
 * Normalise the pipeline GeoJSON features into the app's internal schema.
 * The pipeline already sets: id, height, estimated, type, name, levels,
 * source, khan, hasHeight — but we ensure defaults for safety.
 */
function normalizeStaticFeatures(features) {
  return features.map((f) => {
    const p = f.properties || {}
    return {
      ...f,
      properties: {
        id:        p.id ?? p.osm_id ?? Math.random(),
        height:    p.height ?? null,
        levels:    p.levels ?? null,
        type:      p.type || 'yes',
        name:      p.name || null,
        amenity:   p.amenity || null,
        source:    p.source || 'static',
        khan:      p.khan || null,
        hasHeight: !!p.hasHeight || (p.height > 0),
        estimated: !!p.estimated,
      },
    }
  })
}

/**
 * Fetch buildings from the OSMBuildings anonymous tile API for a given viewport bbox.
 * The API only serves zoom level 15 tiles.
 *
 * Endpoint: https://{a|b|c}.data.osmbuildings.org/0.2/anonymous/tile/15/{x}/{y}.json
 */
export async function fetchOSMBuildingsTiles(bbox, signal) {
  const [south, west, north, east] = bbox
  const tiles = bboxToZ15Tiles(west, south, east, north)

  const SUBDOMAINS = ['a', 'b', 'c']
  const results = []
  const seenIds = new Set()

  await Promise.all(
    tiles.map(async ({ x, y }, i) => {
      const sub = SUBDOMAINS[i % 3]
      const url = `https://${sub}.data.osmbuildings.org/0.2/anonymous/tile/15/${x}/${y}.json`
      try {
        const res = await fetch(url, { signal })
        if (!res.ok) return
        const data = await res.json()
        for (const f of (data.features || [])) {
          const fid = f.properties?.id || f.id || `${x}_${y}_${Math.random()}`
          if (seenIds.has(fid)) continue
          seenIds.add(fid)
          results.push(normalizeOSMBFeature(f))
        }
      } catch (e) {
        if (e.name === 'AbortError') throw e
        // tile failed — silently skip
      }
    })
  )

  return results
}

function normalizeOSMBFeature(f) {
  const p = f.properties || {}
  // OSMBuildings returns height as a number directly
  const height = p.height != null ? parseFloat(p.height) : null
  return {
    ...f,
    properties: {
      id:        p.id || Math.random(),
      height,
      levels:    p.levels ?? null,
      type:      p.buildingType || p.type || 'yes',
      name:      p.name || null,
      amenity:   null,
      source:    'osmbuildings',
      khan:      null,
      hasHeight: height !== null && height > 0,
      estimated: false,
    },
  }
}

/**
 * Convert a lon/lat bbox to all zoom-15 XYZ tile coordinates that intersect it.
 */
function bboxToZ15Tiles(west, south, east, north) {
  const z = 15
  const tiles = []
  const [xMin, yMax] = lonLatToTile(west, south, z)
  const [xMax, yMin] = lonLatToTile(east, north, z)
  for (let x = xMin; x <= xMax; x++) {
    for (let y = yMin; y <= yMax; y++) {
      tiles.push({ x, y })
    }
  }
  return tiles
}

function lonLatToTile(lon, lat, z) {
  const n = Math.pow(2, z)
  const x = Math.floor((lon + 180) / 360 * n)
  const latRad = lat * Math.PI / 180
  const y = Math.floor((1 - Math.log(Math.tan(latRad) + 1 / Math.cos(latRad)) / Math.PI) / 2 * n)
  return [x, y]
}
